spring.application.name=ticket-triage
spring.datasource.url=jdbc:mysql://localhost:3306/ticket_triage
spring.datasource.username=root
spring.datasource.password=Shoeb786
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true